environment:
  matrix:
    - nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - yarn --version
  - yarn
  - yarn test:veyor

build: off
